version: '3'

networks:
    total:
        driver: bridge

services:
    redis:
        image: redis:latest
        command: redis-server /etc/redis/redis.conf
        networks:
            - total
        volumes:
            - ./redis_data:/data
            - ./config/redis.conf:/etc/redis/redis.conf
        ports:
            - "6379:6379"
        restart: always